name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi @${{ github.actor }}, thanks for opening this issue.'
        pr-message: 'Hi @${{ github.event.pull_request.user.login }}, Thank you for taking your time and effort for your contribution, we truly value it. :tada:'
